### ISSUE TITLE
怎么让 多个不同的键对应 同一个值啊？

### ISSUE THREAD

**Issue by mrchenxxx** [LongTengDao/toml-lang#4]
类似于这种写法` '网址' = '网站' = '地址' = 'baidu.com'`

**Comment by LongTengDao** [comment]
TOML 不支持这种写法。

原因是 TOML 的原则是，一定要直观简洁没有歧义（Obvious）。

而且尤其不会为了非最佳实践的理论用法，开辟各种可选的书写形式。

你说的这个需求倒不算是伪需求，有时候是真实存在的，但由于不那么根本性重要，所以经过取舍，不值得为此伤害直观的原则。

当然，这种语法对于直观性的影响没有那么大，如果这个需求真的非常普遍而重要，也不是不能加上。

只是从多年编程经验来看，还没到那个地步。因为在真实的使用场景中，很难找到非如此不可的最佳实践案例。（这也意味着，如果有，你可以发出来，社区是会考虑讨论加入它的。你在问题中给出的案例，更像是思想实验，不太像是实际需求。）

相关的争议和讨论还有，要不要加入变量（`key = $value`、`key = $value * 2`），不过这个对直观性的影响就比较大了，所以通过的可能性更低。

**Comment by mrchenxxx** [comment]
> TOML 不支持这种写法。
> 
> 原因是 TOML 的原则是，一定要直观简洁没有歧义（Obvious）。
> 
> 而且尤其不会为了非最佳实践的理论用法，开辟各种可选的书写形式。
> 
> 你说的这个需求倒不算是伪需求，有时候是真实存在的，但由于不那么根本性重要，所以经过取舍，不值得为此伤害直观的原则。
> 
> 当然，这种语法对于直观性的影响没有那么大，如果这个需求真的非常普遍而重要，也不是不能加上。
> 
> 只是从多年编程经验来看，还没到那个地步。因为在真实的使用场景中，很难找到非如此不可的最佳实践案例。（这也意味着，如果有，你可以发出来，社区是会考虑讨论加入它的。你在问题中给出的案例，更像是思想实验，不太像是实际需求。）
> 
> 相关的争议和讨论还有，要不要加入变量（`key = $value`、`key = $value * 2`），不过这个对直观性的影响就比较大了，所以通过的可能性更低。

谢谢 晓得了
